### PR TITLE
Update jogamp to libgdx 1.8.1-SNAPSHOT

### PR DESCRIPTION
**Pull request by bgroenks96**
This is a resubmission of #10 with the commit history intact.

The faulty gitignore change is reverted by 29110ab.

Note: See [this most recent branch](https://github.com/bgroenks96/libgdx/commits/gdx-1.9.1-SNAPSHOT) for 1.9.1-SNAPSHOT merge and additional bug fixes.

### CODE REVIEW

**Comment by gouessej** [comment]
Please can you minimize the alignment changes? It's really difficult for me to see what has changed in the JogAmp backend.

**Comment by gouessej** [comment]
Please don't reorder the methods in this commit. You can do the cleanup later in a separate commit but I have to see clearly what is different.

**Comment by bgroenks96** [comment]
@gouessej A lot of those were done automatically by my IDE, sorry about that. I'm not sure how I can undo the alignment changes without reverting all of my work though (or doing a really complicated git diff).

I don't remember reordering any methods. Can you point me to a specific place you're referring to? The only thing I reordered (iirc) was the Jogl**DisplayMode inner classes (I moved them to the bottom of the files along with the Jogl**Monitor classes).

**Comment by bgroenks96** [comment]
As a further note, there were a lot of API changes, so some of the method deletions that may look like re-ordering are actually replacements. Most of the display-mode related methods got replaced with new implementations according to the new `Graphics` specification.

**Comment by bgroenks96** [comment]
I just moved the rest of the backend fixes over from the 1.9.1 branch since they aren't specific to that version.

See 706a261 for the latest tree state.

**Pull request merged**
