### PR TITLE
Merge release 1.9.2 from GDX master.

### PR DESCRIPTION
**Pull request by bgroenks96**

### CODE REVIEW

**Comment by gouessej** [comment]
Why "libgdxNightlyVersion = "1.9.3-SNAPSHOT""?

**Comment by bgroenks96** [comment]
Well, when the version gets incremented to '1.9.2' the nightly build version becomes '1.9.3-SNAPSHOT.'

It seem odd though that the DependencyBank class still has '1.9.1' as the 'libgdxVersion'. That might be an oversight from the LibGDX guys?

**Comment by gouessej** [comment]
@badlogic Can you tell us whether there is something wrong with the dependency bank still using 1.9.1 as the 'libgdxVersion'?

**Comment by badlogic** [comment]
Yeah the build of gdx-setup hung itself appearently. Fixing, thanks for
reporting.

**Comment by bgroenks96** [comment]
Fix cherry-picked in with 182b7c2

**Pull request merged**
